# -*- coding: utf-8 -*-
"""TimeSeries -Decomposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkqp1YDyU7t-6RiWObFpPzhIMArfT8So
"""

import yfinance as yf

import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

stock_data = yf.download('MSFT',start='2022-01-01')

stock_data.head(10)

plt.figure(figsize=(12,6))
plt.plot(stock_data.index,stock_data['Close'],label='Close Price', color='#FF914D')

plt.title("AAPL Stock price over time")

plt.xlabel('Date')
plt.ylabel('Price in USD')
plt.legend()

plt.grid(True)
plt.show()

"""# Time Series Decomposition"""

from statsmodels.tsa.seasonal import seasonal_decompose

decomposition_additive =  seasonal_decompose(stock_data['Close'],model='additive',period=30)
decomposition_multiplicative = seasonal_decompose(stock_data['Close'],model='multiplicative',period=30)

trend_additive = decomposition_additive.trend
trend_multiplicative = decomposition_multiplicative.trend
seasonal_additive = decomposition_additive.seasonal
seasonal_multiplicative = decomposition_multiplicative.seasonal
residual_additive = decomposition_additive.resid
residual_multiplicative = decomposition_multiplicative.resid

plt.figure(figsize=(14,10))
plt.subplot(411)
plt.plot(stock_data['Close'],label='Original',color='#FF914D')
plt.legend(loc='upper left')
plt.subplot(412)
plt.plot(trend_additive,label='Trend',color='#FF914D')
plt.legend(loc='upper left')
plt.subplot(413)
plt.plot(seasonal_additive,label='Seasonal',color='#FF914D')
plt.legend(loc='upper left')
plt.subplot(414)
plt.plot(residual_additive,label='Residual',color='#FF914D')
plt.legend(loc='upper left')
plt.tight_layout()
plt.show()

